import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import { fileURLToPath } from "url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));

const packageInfo = JSON.parse(readFileSync(
    resolve(__dirname, "../package.json"),
    "utf8"
));

const buildDate = new Date();
const built = `${buildDate.getUTCFullYear()}-${String(buildDate.getUTCMonth() + 1).padStart(2, "0")}-${String(buildDate.getUTCDate()).padStart(2, "0")}`;

const output = `// Do not edit this file - it is generated automatically at build time

export const BUILD_DATE = "${built}";
export const VERSION = "${packageInfo.version}";
`;

writeFileSync(
    resolve(__dirname, "../source/shared/library/version.ts"),
    output
);
